name: ecommerce_app_login
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icons and Images
  cupertino_icons: ^1.0.8
  fluttericon:  ^2.0.0
  cached_network_image:  ^3.4.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Online
  http: ^1.3.0
  url_launcher: ^6.3.1

  # Local Database
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path:  ^1.9.1
  flutter_image_compress: ^2.4.0
  file_picker: 10.1.0
  permission_handler: ^12.0.0+1 

  # State management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  meta: ^1.16.0
  equatable: ^2.0.7
  
  # Fonts
  google_fonts: ^6.2.1

  # Utils
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    